package com.exampro.app.data.db

import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import platform.Foundation.NSHomeDirectory

actual object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    // Note: AppDatabase_Impl is generated by Room.
    // It will stay red until a successful iOS build.
    actual override fun initialize(): AppDatabase = AppDatabase_Impl()
}

actual fun getDatabaseBuilder(): RoomDatabase.Builder<AppDatabase> {
    // This finds the internal folder on the iPhone to save the DB
    val dbFilePath = NSHomeDirectory() + "/exampro_db.db"

    return Room.databaseBuilder<AppDatabase>(
        name = dbFilePath,
        // The factory is required on iOS to link the generated code
        factory = { AppDatabaseConstructor.initialize() }
    )
}